export const INI_FICHAS = [{
    frame: 0,
    nombre: "pueblo ini",
    nivel: 0,
    colocada: false,
    oculta: false,
    pueblo: true,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    tesoro: 0,
    tropa: []
},
{
    frame: 8,
    nombre: "mina madera ini",
    nivel: 0,
    colocada: false,
    oculta: false,
    pueblo: false,
    minaMadera: true,
    minaPiedra: false,
    minaOro: false,
    tesoro: 0,
    tropa: []
},
{
    frame: 16,
    nombre: "mina piedra ini",
    nivel: 0,
    colocada: false,
    oculta: false,
    pueblo: false,
    minaMadera: false,
    minaPiedra: true,
    minaOro: false,
    tesoro: 0,
    tropa: [{ jugador: null, 
        tropas: [{ tipo: "leva",
            cantidad: 1,
            vida: 1,
            ataque: 1,
            movimiento: 2,
            movido: 0,
            velocidad: 1,
            nivel: 1,
            distanciaDeAtaque: 0
    }] }]
},
{
    frame: 24,
    nombre: "ficha 1",
    nivel: 1,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    tesoro: 0,
    tropa: [{ jugador: null, 
        tropas: [{ tipo: "leva",
            cantidad: 1,
            vida: 1,
            ataque: 1,
            movimiento: 2,
            movido: 0,
            velocidad: 1,
            nivel: 1,
            distanciaDeAtaque: 0
    }] }]
},
{
    frame: 32,
    nombre: "ficha 2",
    nivel: 1,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    tesoro: 1,
    tropa: []
},
{
    frame: 1,
    nombre: "ficha 3",
    nivel: 1,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    tesoro: 1,
    tropa: [{ jugador: null, 
        tropas: [{ tipo: "leva",
            cantidad: 1,
            vida: 1,
            ataque: 1,
            movimiento: 2,
            movido: 0,
            velocidad: 1,
            nivel: 1,
            distanciaDeAtaque: 0
    }] }]
},
{
    frame: 9,
    nombre: "ficha 4",
    nivel: 1,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    tesoro: 0,
    tropa: []
},
{
    frame: 17,
    nombre: "ficha 5",
    nivel: 1,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    tesoro: 0,
    tropa: [{ jugador: null, 
        tropas: [{ tipo: "leva",
            cantidad: 1,
            vida: 1,
            ataque: 1,
            movimiento: 2,
            movido: 0,
            velocidad: 1,
            nivel: 1,
            distanciaDeAtaque: 0
    }] }]
},
{
    frame: 25,
    nombre: "ficha 6",
    nivel: 1,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    tesoro: 0,
    tropa: []
},
{
    frame: 33,
    nombre: "ficha 7",
    nivel: 1,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    tesoro: 0,
    tropa: []
},
{
    frame: 2,
    nombre: "ficha 8",
    nivel: 1,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 1,
    tesoro: 0,
    tropa: []
},
{
    frame: 10,
    nombre: "ficha 9",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 1,
    tesoro: 0,
    tropa: []
},
{
    frame: 26,
    nombre: "ficha 11",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 1,
    tropa: [{ jugador: null, 
        tropas: [{ tipo: "soldado",
            cantidad: 1,
            vida: 2,
            ataque: 2,
            movimiento: 2,
            movido: 0,
            velocidad: 1,
            nivel: 2,
            distanciaDeAtaque: 0
    }] }]
},
{
    frame: 34,
    nombre: "ficha 12",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 2,
    tropa: [{ jugador: null, 
        tropas: [{ tipo: "leva",
            cantidad: 2,
            vida: 1,
            ataque: 1,
            movimiento: 2,
            movido: 0,
            velocidad: 1,
            nivel: 1,
            distanciaDeAtaque: 0
    }] }]
},
{
    frame: 3,
    nombre: "ficha 13",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 0,
    tropa: []
},
{
    frame: 11,
    nombre: "ficha 14",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 0,
    tropa: []
},
{
    frame: 19,
    nombre: "ficha 15",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 0,
    tropa: []
},
{
    frame: 28,
    nombre: "ficha 16",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 0,
    tropa: []
},
{
    frame: 36,
    nombre: "ficha 17",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 0,
    tropa: []
},
{
    frame: 4,
    nombre: "ficha 18",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 0,
    tropa: []
},
{
    frame: 12,
    nombre: "ficha 19",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: false,
    minaMadera: true,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 0,
    tropa: [{ jugador: null, 
        tropas: [{ tipo: "leva",
            cantidad: 1,
            vida: 1,
            ataque: 1,
            movimiento: 2,
            movido: 0,
            velocidad: 1,
            nivel: 1,
            distanciaDeAtaque: 0
    }] }]
},
{
    frame: 20,
    nombre: "ficha 20",
    nivel: 2,
    colocada: false,
    oculta: true,
    pueblo: true,
    minaMadera: false,
    minaPiedra: false,
    minaOro: false,
    minaTecnologia: 0,
    tesoro: 0,
    tropa: [{ jugador: null, 
        tropas: [{ tipo: "leva",
            cantidad: 2,
            vida: 1,
            ataque: 1,
            movimiento: 2,
            movido: 0,
            velocidad: 1,
            nivel: 1,
            distanciaDeAtaque: 0
    }] }]
}
];

export const INI_EDIFICIOS = [{
    nombre: 'ayuntamiento',
    posicion: -1,
    nivel: 1,
    oro: 2,
    madera: 0,
    piedra: 0,
    puntos: 1,
    frame: 0
},
{
    nombre: 'almacen',
    posicion: -1,
    nivel: 1,
    oro: 1,
    madera: 1,
    piedra: 0,
    puntos: 1,
    frame: 1
},
{
    nombre: 'cuartel',
    posicion: -1,
    nivel: 1,
    oro: 3,
    madera: 1,
    piedra: 0,
    puntos: 1,
    frame: 2
},
{
    nombre: 'estatua',
    posicion: -1,
    nivel: 1,
    oro: 1,
    madera: 0,
    piedra: 0,
    puntos: 4,
    frame: 3
},
{
    nombre: 'biblioteca',
    posicion: -1,
    nivel: 1,
    oro: 3,
    madera: 1,
    piedra: 0,
    puntos: 1,
    frame: 4
},
{
    nombre: 'mercado',
    posicion: -1,
    nivel: 1,
    oro: 1,
    madera: 0,
    piedra: 0,
    puntos: 1,
    frame: 5
},
{
    nombre: 'arqueria',
    posicion: -1,
    nivel: 2,
    oro: 3,
    madera: 2,
    piedra: 0,
    puntos: 2,
    frame: 6
},
{
    nombre: 'atalaya',
    posicion: -1,
    nivel: 2,
    oro: 4,
    madera: 1,
    piedra: 0,
    puntos: 2,
    frame: 7
},
{
    nombre: 'banco',
    posicion: -1,
    nivel: 2,
    oro: 3,
    madera: 1,
    piedra: 0,
    puntos: 2,
    frame: 8
},
{
    nombre: 'laboratorio',
    posicion: -1,
    nivel: 2,
    oro: 5,
    madera: 2,
    piedra: 0,
    puntos: 2,
    frame: 9
},
{
    nombre: 'tesoreria',
    posicion: -1,
    nivel: 3,
    oro: 4,
    madera: 2,
    piedra: 1,
    puntos: 3,
    frame: 10
},
{
    nombre: 'establos',
    posicion: -1,
    nivel: 3,
    oro: 5,
    madera: 2,
    piedra: 1,
    puntos: 3,
    frame: 11
},
{
    nombre: 'coliseo',
    posicion: -1,
    nivel: 3,
    oro: 5,
    madera: 2,
    piedra: 1,
    puntos: 10,
    frame: 12
},
{
    nombre: 'universidad',
    posicion: -1,
    nivel: 3,
    oro: 7,
    madera: 2,
    piedra: 1,
    puntos: 3,
    frame: 13
},
{
    nombre: 'teatro',
    posicion: -1,
    nivel: 2,
    oro: 3,
    madera: 1,
    piedra: 0,
    puntos: 7,
    frame: 14
},
{
    nombre: 'armeria',
    posicion: -1,
    nivel: 2,
    oro: 3,
    madera: 0,
    piedra: 1,
    puntos: 2,
    frame: 15
}];